### PR TITLE
Bump to release 6.2.2

### PR DESCRIPTION
**Pull request by velioglu**
Bump to release 6.2.2 by changing the corresponding version numbers.

### CODE REVIEW

**Comment by begriffs** [comment]
I verified that the cloudformation template resolves, so this looks good to me. 🚢

**Comment by begriffs** [comment]
Fixes #222

**Comment by begriffs** [comment]
By the way, having this branch named `v6.2.2` confuses Read the Docs. I marked the branch as "private" in their interface. For future pull request branch names it's better to choose one that isn't formatted as a version name.

**Comment by sumedhpathak** [comment]
Trying the CF template, it gives me:
```
postgres=# show citus.version;
 citus.version 
---------------
 6.2.1
(1 row)
```

**Comment by sumedhpathak** [comment]
The package seems OK:

```
[ec2-user@ip-10-192-0-172 ~]$ sudo yum install citus62_96;
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                                                                            | 2.1 kB     00:00     
amzn-updates/latest                                                                                                                                         | 2.3 kB     00:00     
citusdata_community/x86_64/signature                                                                                                                        |  836 B     00:00     
citusdata_community/x86_64/signature                                                                                                                        | 1.0 kB     00:00 ... 
1045 packages excluded due to repository priority protections
Package citus62_96-6.2.2.citus-1.el6.x86_64 already installed and latest version
Nothing to do
```

**Comment by sumedhpathak** [comment]
I also verified the right template is being picked. I am verifying the template manually, and still exhibits the same problem. @velioglu @byucesoy any ideas?

**Comment by sumedhpathak** [comment]
Ok, @jasonmp85 informed me that the citus.version wasn't updated, since we tagged before we updated this. However, we expect this package is still 6.2.2. Is there a way to validate this? 
@byucesoy @jasonmp85 Could we document this step (or automate) so we don't miss this in the future?

**Comment by jasonmp85** [comment]
@sumedhpathak sorry for the confusion. The `v6.2.2` tag was created before I realized the version in the `configure.in` should have been updated.

We have a lot of conventions around releasing and many of them would be pretty straightforward to implement in code, so maybe adding a script or two to `citusdata/tools` could help.

**Comment by sumedhpathak** [comment]
Then overall approved. There appears to be no easy way to verify this is actually pulling 6.2.2 due to the tag mishap. @begriffs Should we squash and merge?

**Comment by begriffs** [comment]
Sure, I'll merge and cherry-pick to 6.2.

**Comment by jasonmp85** [comment]
> There appears to be no easy way to verify this is actually pulling 6.2.2 due to the tag mishap. @begriffs Should we squash and merge?

If you really want to check you can ssh into the EC2 box and print out the package version that is installed.

**Pull request merged**
