### PR TITLE
Lighter highlighting

### PR DESCRIPTION
**Pull request by craigkerstiens**

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for the UI tweak.

However can you fix up this PR? It includes changes from other pull requests. This is because you have opened each pull request branch from the end of the last:

branches building

What you should do is each time you open a pull request, do `git checkout master` and then create the branch from there:

all from master

That way pull requests won't accumulate each other's changes.

**Comment by begriffs** [comment]
In #510 I added instructions for how to remove unwanted commits from a branch.

**Comment by begriffs** [comment]
(FYI, it's kind of annoying but changing the sass alone won't trigger the css to be built on docs, you have to explicitly run `grunt sass` in the `_themes` folder. I did that just now and committed the new css files.)

**Comment by sumedhpathak** [comment]
@begriffs Could you review and merge? I can't quite tell what highlighting has changed based on the changes.

**Comment by begriffs** [comment]
Yep it looks good to me. It changes the highlight color around terms in the search results.

**Pull request merged**
