### PR TITLE
Update write_throughput_benchmark.rst

### PR DESCRIPTION
**Pull request by steffenix**
Fix example

### CODE REVIEW

**Comment by begriffs** [comment]
@steffenix thanks for the pull request. Is `setrandom` deprecated?

**Comment by steffenix** [comment]
Got replaced in 9.6
https://www.postgresql.org/docs/9.6/static/release-9-6.html

**Comment by begriffs** [comment]
Just reproduced the problem you reported. With postgres-contrib 10 I got the error `insert.sql:4: invalid command in command "setrandom"`.

Your change looks good but there are a few other things to fix:

* Our [install pgbench](https://docs.citusdata.com/en/v7.1/extra/write_throughput_benchmark.html#install-pgbench) instructions specify postgres 9.5. Following those instructions would make the benchmarking guide work without a problem. However I agree with you that we should use a newer version because it's more likely what people have on their machines already. Could you update the install instructions?
* The [update throughput](https://docs.citusdata.com/en/v7.1/extra/write_throughput_benchmark.html#id2) section also has sql with `setrandom`.

Would you like to update your pull request with these additions?

**Comment by steffenix** [comment]
OK I will have alook and update my pull request.

**Comment by steffenix** [comment]
I have changed the version to 10.

**Comment by steffenix** [comment]
I have done and cleanup the mess that was introduced by the merge.

**Comment by begriffs** [comment]
Thank you!

**Pull request merged**
