### PR TITLE
Add install instructions for pg_auto_failover enterprise from MS

### PR DESCRIPTION
**Pull request by JelteF**
pg_auto_failover enterprise packages are now live on microsoft package hosting.
This updates the install instructions to include instructions to install them.

### CODE REVIEW

**Comment by jonels-msft** [comment]
@JelteF just letting you know I see this PR and will review it early next week.

**Comment by JelteF** [comment]
I just addressed your comment (and fixed the title of the last section). Installing pg_auto_failover is now marked as optional.

**Comment by JelteF** [comment]
I think this can be merged now. @jonels-msft do you agree?

**Comment by jonels-msft** [comment]
Thanks for the reminder.

Let me add a few notes to motivate the content, and then I'll merge it.

**Pull request merged**
