### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by fossygirl**
Adding Code of Conduct to /citus_docs repo to reflect adopting the Microsoft Open Source Code of Conduct.

cc @clairegiordano @pinodeca

### CODE REVIEW

**Comment by jonels-msft** [comment]
Looks like GitHub [suggests](https://docs.github.com/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) the filename `CODE_OF_CONDUCT.md`. Can you rename the file please?

**Comment by fossygirl** [comment]
@jonels-msft I believe that should be done based on this commit: https://github.com/citusdata/citus_docs/pull/1098/commits/9102db857a2336d4772377edb257ee8fcafb92ee 

Can you verify if you see that as well?

**Comment by jonels-msft** [comment]
Hm, the file still appears to be called `CODEOFCONDUCT.md` on this pull request branch (`fossygirl:patch-3`). Can you try again please with the underscores?

**Comment by fossygirl** [comment]
Apologies, my bad! I missed that. Should be correct now.

**Pull request merged**
