### PR TITLE
Docs updates (mainly outputs & table descriptions)

### PR DESCRIPTION
**Pull request by naisila**
I tested the _Quick Tutorials_, _Develop_ and _FAQ_ sections.
As a result: some outdated outputs, table descriptions. There is also a change in the default of `citus.node_connection_timeout`, and some small typos.

### CODE REVIEW

**Review by jonels-msft — APPROVED** [review]
Thanks for all the fixes!

I notice that there's one "XX000" error remaining in reference/common_errors.rst (`ERROR:  XX000: could not connect to any active placements`). Should that message change as well?

**Review by onurctirtir — APPROVED** [review]
Please address Joe's comment before merging

https://github.com/citusdata/citus_docs/pull/962#pullrequestreview-529343371

**Comment by NaisilaPuka** [comment]
@jonels-msft thanks for approval. I also fixed that error message you said.

I forgot to mention in the description that my task was to test specific sections (not all) for this release. I didn't test the Troubleshoot section. I will edit the description now.

@onurctirtir okay thanks

**Comment by jonels-msft** [comment]
I'll cherry-pick this to v9.4 and v9.5

**Pull request merged**
