### PR TITLE
Update version string from 5.0 to 5.1

### LINKED ISSUE #50: Update version string on 5.1 doc branch
From 5.0 to 5.1

### PR DESCRIPTION
**Pull request by begriffs**
A few notes

* The top menu is added by the theme and hardcodes `/docs/citus/5.1/index.html` for its Documentation link. This is fine when hosted how we currently do but will need to be changed if/when we move to readthedocs.
* I didn't change the **Administration → Upgrading to Citus 5** section which still has many references to 5.0. I'm thinking that in context 5.0 indicates a major version and that the minor version is not relevant. I could change references in the section from "5.0" to "5" to emphasize this.

Closes #50

### CODE REVIEW

**Comment by sumedhpathak** [comment]
@begriffs could we also update the upgrade process. I agree that it indicates upgrading from one major version to another, but it would be useful to have consistent terminology around what version of Citus they are looking at/using.

**Comment by sumedhpathak** [comment]
After that its a 🚢

**Comment by begriffs** [comment]
@sumedhpathak PR #58 adjusts the versions mentioned in the upgrade section. Is it the change you had in mind?

**Comment by sumedhpathak** [comment]
Ok yes, Then this looks good to ship.

On Thu, May 12, 2016 at 2:46 PM, Joe Nelson <notifications@github.com>
wrote:

> @sumedhpathak <https://github.com/sumedhpathak> PR #58
> <https://github.com/citusdata/citus_docs/pull/58> adjusts the versions
> mentioned in the upgrade section. Is it the change you had in mind?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/citusdata/citus_docs/pull/56#issuecomment-218895418>
>



-- 
*Sumedh Pathak*
Citus Data
650.422.9797
sumedh@citusdata.com

**Comment by begriffs** [comment]
I'll wait to merge this until the installation/tutorial restructuring PR #55 has been merged and the 5.0 branch created.

This and the other 5.1 changes can then start going into master.

**Comment by begriffs** [comment]
OK v5.0 branch created, time to ship this.

**Pull request merged**
