### PR TITLE
Ozgun's edits

### PR DESCRIPTION
**Pull request by lithp**
A PR to make it easier to make comments

### CODE REVIEW

**Comment by ozgune** [comment]
@lithp -- The content in this pull request is different than the one in https://citus-doc-preview-pr-118.herokuapp.com/tech_soln/real_time_analytics.html

Which one should I look at?

**Comment by lithp** [comment]
Hey, that link is the link for this PR: https://github.com/citusdata/citus_docs/pull/118

That's the one I've been working off of.

**Comment by begriffs** [comment]
@lithp I'm assuming that this PR is OK to close now that #118 and #164 are merged, right?

**Comment by lithp** [comment]
@begriffs yep, sorry!

**Pull request closed without merging**
