### PR TITLE
Update tutorials to Citus 6.1

### PR DESCRIPTION
**Pull request by begriffs**
Built new binaries using Citus v6.1.0-rc2 and added them to S3. Tested tutorial instructions on OS X and Ubuntu.

### CODE REVIEW

**Comment by sumedhpathak** [comment]
@begriffs Did you run into any issues on Mac? I'm getting an error with the ingest script on Mac's. The Linux one seems to work fine on an AWS instance.

**Comment by begriffs** [comment]
I did run it on Mac. Encountered an intermittent failure that seems to be related to the Wikipedia API. See if the problem clears up if you run it again.

**Comment by sumedhpathak** [comment]
Ok, Looks good. I was distracted for a fair bit by the script not working on my Mac in the public wi-fi network. It seems to work reliably at home. Also tested the Linux bundle on an AWS machine.

**Comment by begriffs** [comment]
I opened https://github.com/citusdata/citus-tutorial/issues/10 about a way to potentially make the script more robust.

**Pull request merged**
