### PR TITLE
Fixing small typos and query inconsistencies

### PR DESCRIPTION
**Pull request by NaisilaPuka**
While I was doing some release tests on the documentation, I found some small typos and some query inconsistencies, like hourly-daily confusion in partitions, lack of schema specification in a pg_partman function etc.

### CODE REVIEW

**Comment by begriffs** [comment]
Actually maybe hold off merging for a little, while I look into potential git issues we talked about in slack.

**Comment by begriffs** [comment]
⚠️ I moved the master branch back to its old commit, which caused a bunch of false commits to appear in this pull request from the duplicate git history. @NaisilaPuka please run the following locally to repair this branch:

```bash
# inform git how things changed on github
git fetch

# attach your branch to the updated master
git checkout typos-r7.5
git rebase origin/master

# give it one more check to see that the diff is what you expect
git diff origin/master

# then force push just the single branch
git push --force -u origin typos-r7.5:typos-r7.5
```

After that let's let @sumedhpathak give it a final review.

**Comment by sumedhpathak** [comment]
@NaisilaPuka I'll wait until you fix up this branch for the review. Could you let me know when that is done? Thanks.

**Comment by NaisilaPuka** [comment]
Thanks @begriffs !
@sumedhpathak it's done. Thanks!

**Pull request merged**
