### PR TITLE
Bump Citus documentation to 6.2.0

### PR DESCRIPTION
**Pull request by byucesoy**

### CODE REVIEW

**Comment by begriffs** [comment]
Hey thanks Burak. I'm actually working on this already in #369 so I'm going to close this PR.

**Comment by byucesoy** [comment]
I opened this PR because we have a checklist(https://github.com/citusdata/citus/issues/1415) for release items and this is one of the items. It only consist of changing cf template link and the version in conf.py. 

We are changing this two places as a part of packaging process for several releases. How should we arrange work division here?

@jasonmp85

**Comment by begriffs** [comment]
Ah I see. I was using a checklist as well, https://github.com/citusdata/citus_docs/issues/366, which I guess  overlaps yours.

Actually we could re-open this PR for the CF template link change because I wasn't sure what the correct new value should be.

**Comment by begriffs** [comment]
...or I can copy the CF template change into my own PR because it has a few other upgrade things in it as well.

**Comment by begriffs** [comment]
(Copied the code)

**Pull request closed without merging**
